name: Build Windows NoKinect

on:
  push:
    branches:
      - master
      - '*Test*'

jobs:
  Build:
    runs-on: [self-hosted, windows]
    env:
      project: PopCameraDevice
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0
      
    - name: Windows
      uses: NewChromantics/PopAction_BuildWindows@v1
      with:
        BuildPlatform: x64
        BuildConfiguration: Debug_NoKinect
        # would be nice to extract this from visual studio
        BuildDirectory: PopCameraDevice.visualstudio\x64\Debug_NoKinect
        project: ${{ env.project }}