name: Build Osx

on:
  push:
    branches:
      - master
      - '*Test*'

jobs:
  Test:
    env:
      project: PopCameraDevice
    runs-on: [self-hosted, macOS]

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: "recursive"
      - uses: NewChromantics/PopAction_BuildApple@v1
        with:
          BuildScheme: ${{ env.project }}
          project: ${{ env.project }}