name: Build Linux

on:
  push:
    branches:
      - master
      - '*Test*'

jobs:
  Test:
    env:
      project: PopCameraDevice
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          # tsdk: Disabled as the kinect dependencies break the build
          # - os: ubuntu-latest
          #   type: linux
          #   architecture: x86_64

          - os: Nvidia
            type: linux
            architecture: arm64

          # - os: Pi4
          #   type: linux
          #   architecture: arm64

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: "recursive"
      - name: Linux
        uses: NewChromantics/PopAction_BuildLinux@v1
        with:
          machine: ${{ matrix.config.os }
          architecture: ${{ matrix.config.architecture }}
          project: ${{ env.project }}
