name: Build Apple

env:
  project: PopCameraDevice

on:
  push:
    branches:
      - master
      - '*Test*'

jobs:
  Test:
    name: Universal Build
    runs-on: macos-latest

    steps:
      - name: "Import Apple-Distriubution NewChromantics Signing Certificate"
        uses: devbotsxyz/xcode-import-certificate@master
        with:
          certificate-data: ${{ secrets.APPLE_DIST_NEWCHROMANTICS_P12 }}
          certificate-passphrase: ${{ secrets.APPLE_DIST_NEWCHROMANTICS_PASSWORD }}
          keychain-password: "Hello"

      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - uses: NewChromantics/PopAction_BuildApple@v1.0.11
        with:
          BuildScheme: ${{ env.project }}_Osx
          project: ${{ env.project }}

      # gr: create artifacts so we can test master commits before publishing a tag
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          # tsdk: these env vars are set in each of the actions
          name: ${{ env.UPLOAD_NAME }}
          path: ${{ env.UPLOAD_DIR }}
