name: Build Linux

on:
  push:
    branches:
      - master
      - '*Test*'

jobs:
  Test:
    env:
      project: PopCameraDevice
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          # tsdk: Disabled as the kinect dependencies break the build
          - os: ubuntu-latest
            type: linux
            architecture: x86_64

          - os: Nvidia
            type: linux
            architecture: arm64

          - os: Pi4
            type: linux
            architecture: arm64

    steps:
      # gr: fetch-depth:0 to override tags. To get rid of "existing tag will be clobbered" when we move a tag. This only seems to happen on the pi self runner (git version?)
      - uses: actions/checkout@v1
        with:
          submodules: "recursive"
          fetch-depth: 0
      - name: Linux
        uses: NewChromantics/PopAction_BuildLinux@v1
        with:
          os: ${{ matrix.config.os }}
          project: ${{ env.project }}
