name: Build Linux

on:
  push:
    branches:
      - master
      - '*Test*'

jobs:
  Test:
    env:
      project: PopCameraDevice
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - os: ubuntu-18.04
            type: linux
            arch: x86_64

          # disabled whilst no nvidia runner
          #- os: Nvidia
          #  type: linux
          #  arch: arm64

          # disabled pi whilst pi build machine is offline.
          #- os: Pi4
          #  type: linux
          #  architecture: arm64

    steps:
      # gr: fetch-depth:0 to override tags. To get rid of "existing tag will be clobbered" when we move a tag. This only seems to happen on the pi self runner (git version?)
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          #fetch-depth: 0
      - name: Linux
        uses: NewChromantics/PopAction_BuildLinux@v1
        with:
          os: ${{ matrix.config.os }}
          project: ${{ env.project }}
          arch: ${{ matrix.config.os }}
