name: Build Apple

env:
  project: PopCameraDevice

on:
  push:
    branches:
      - master
      - '*Test*'

jobs:
  Test:
    name: Universal Build
    runs-on: macOS

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - uses: NewChromantics/PopAction_BuildApple@v1.0.9
        with:
          BuildScheme: ${{ env.project }}_Universal
          project: ${{ env.project }}

      # gr: create artifacts so we can test master commits before publishing a tag
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          # tsdk: these env vars are set in each of the actions
          name: ${{ env.UPLOAD_NAME }}
          path: ${{ env.UPLOAD_DIR }}
