name: Build Windows NoKinect

on:
  push:
    branches:
      - master
      - '*Test*'

jobs:
  Build:
    runs-on: windows-latest
    env:
      project: PopCameraDevice
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Windows
      uses: NewChromantics/PopAction_BuildWindows@v1
      with:
        BuildPlatform: x64
        BuildConfiguration: Release_NoKinect
        # would be nice to extract this from visual studio
        BuildDirectory: Build\Release_NoKinect_x64
        project: ${{ env.project }}
