name: Build Apple

env:
  project: PopCameraDevice

on:
  push:
    branches:
      - master
      - '*Test*'

jobs:
  Test:
    name: Universal Build
    runs-on: macOS

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - uses: NewChromantics/PopAction_BuildApple@v1.0.5
        with:
          BuildScheme: ${{ env.project }}_Universal
          project: ${{ env.project }}
